control:
  testnet: true
  debug: true

binance_api:
  base_endpoint: https://fapi.binance.com
  testnet_rest_api_url: https://testnet.binancefuture.com
  webSocket_base_endpoint: wss://fstream.binance.com
  webSocket_base_endpoint_for_testnet: wss://stream.binancefuture.com
  max_weight_per_minute: 1200
  max_order_per_second: 50
  ping_interval: 10
  pong_timeout: 5
  reconnect_attempts: 10
  max_order_per_minute: 100
  recv_window: 5000

index:
  bb_length: 20
  bb_mult: 1.5
  bb_change_rate: 0.1
  bb_change_rate_window: 6
  bb_price_threshold: 0.0005
  rsi_length: 14
  rsi_overbought: 70
  rsi_oversold: 30
  rsi_momentum_offset: 5
  rsi_reversal_offset: 5
  rsi_average_window: 6
  ma_slow_length: 50
  ma_slope_window: 6
  ma_slope_threshold: 0.0025
  atr_period: 14
  average_volume_window: 100

trading:
  symbol_list:
    - BTCUSDT
    - ETHUSDT
    - XRPUSDT
    - BNBUSDT
    - SOLUSDT
    - ADAUSDT
  leverage: 5
  price_protect: true
  activate_price_rate: 0.01
  trailing_percent: 1.2 #百分比%
  max_loss_percent: 0.015
  mean_reversion_tp: 0.018
  mean_reversion_sl: 0.01

risk_control:
  risk_per_trade: 0.005
  max_margin_usage: 0.7
  slippage_percent: 0.5 #百分比%
  max_holding_bars: 6
  max_daily_trades: 5
  max_daily_loss: 0.02
  consecutive_losses: 3
  cooldown_period: 3600
  min_bandwidth_threshold: 0.008
