control:
  testnet: true
  debug: true

binance_api:
  base_endpoint: https://fapi.binance.com
  testnet_rest_api_url: https://testnet.binancefuture.com
  webSocket_base_endpoint: wss://fstream.binance.com
  webSocket_base_endpoint_for_testnet: wss://stream.binancefuture.com
  max_weight_per_minute: 1200
  max_order_per_second: 50
  ping_interval: 60
  pong_timeout: 20
  reconnect_attempts: 5
  max_order_per_minute: 100
  recv_window: 5000

index:
  bb_length: 20
  bb_mult: 2
  rsi_length: 14
  ma_slow_length: 100
  atr_period: 14

trading:
  symbol_list:
    - BTCUSDT
    - ETHUSDT
    - SOLUSDT
    - XRPUSDT
    - ADAUSDT
  leverage: 5
  price_protect: true
  trailing_percent: 1.2
  max_loss_percent: 0.012
  mean_reversion_tp: 0.018
  mean_reversion_sl: 0.01

risk_control:
  risk_per_trade: 0.02
  max_margin_usage: 0.7
  slippage_percent: 0.005
  max_holding_bars: 6
  max_daily_trades: 10
  max_daily_loss: 0.1
  cooldown_period: 3600
  exit_ratio_list: [0.5, 0.3, 0.2]
  confirm_candle: 1
