control:
  testnet: true

binance_api:
  base_endpoint: https://fapi.binance.com
  testnet_rest_api_url: https://testnet.binancefuture.com
  webSocket_base_endpoint: wss://ws-fapi.binance.com/ws-fapi/v1
  webSocket_base_endpoint_for_testnet: wss://testnet.binancefuture.com/ws-fapi/v1
  max_weight_per_minute: 1200
  max_order_per_second: 10
  ping_interval: 180  
  pong_timeout: 600   
  max_order_per_minute: 100

index:
  bb_length: 20
  bb_mult: 2
  rsi_length: 14
  ma_slow_length: 100
  atr_period: 14

trade:
symbol_list: ['BTCUSDT', 'ETHUSDT', 'SOLUSDT','XRPUSDT', 'ADAUSDT']
  leverage: 5
  trailing_percent: 0.012
  max_loss_percent: 0.012
  mean_reversion_tp: 0.018
  mean_reversion_sl: 0.01
  confirm_candle: 1

risk_control:
  risk_per_trade: 0.02
  max_margin_usage: 0.7
  slippage_percent: 0.005
  max_holding_bars: 6
  max_daily_trades: 10
  max_daily_loss: 0.1
  cooldown_period: 3600
  exit_ratio_list: [0.5, 0.3, 0.2]

